spring.application.name=demojournal
spring.datasource.url=jdbc:postgresql://localhost:5432/Journalbd
spring.datasource.username=postgres
spring.datasource.password=sastp31256*@1wsq
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.hiddenmethod.filter.enabled=true